language: python
python:
    - "3.5"

install:
    - pip install -r requirements.txt
    - pip install codecov

# run scripts
script:
   - make test
 # - coverage erase
 # - coverage run app.py && coverage html

#after_success:
 # - codecov
